### ISSUE TITLE
Are you compatible with Spark release 2.2.0?

### ISSUE THREAD

**Issue by pranasblk** [dmagda/IgniteSparkIoT#1]
It's nice to see a simple example on how to set-up Ignite & Apache from IDE. Thanks!
I'm having troubles in using latest released version. Would you mind checking if some transitive dependencies are not retrieved properly?

Thanks again,
P

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.ui.SparkUI.setStreamingJobProgressListener(Lorg/apache/spark/scheduler/SparkListener;)V
	at org.apache.spark.streaming.ui.StreamingTab.<init>(StreamingTab.scala:41)
	at org.apache.spark.streaming.StreamingContext.<init>(StreamingContext.scala:192)
	at org.apache.spark.streaming.StreamingContext.<init>(StreamingContext.scala:85)
	at org.apache.spark.streaming.api.java.JavaStreamingContext.<init>(JavaStreamingContext.scala:138)
	at org.apache.ignite.iot.SparkStreamerStartup.main(SparkStreamerStartup.java:71)
17/08/22 18:27:25 INFO SparkContext: Invoking stop() from shutdown hook
17/08/22 18:27:25 INFO SparkUI: Stopped Spark web UI at http://10.0.1.6:4040
```

Complied with 
```
    <dependencies>

        <dependency>
            <groupId>org.apache.ignite</groupId>
            <artifactId>ignite-flink</artifactId>
            <version>2.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.ignite</groupId>
            <artifactId>ignite-spring</artifactId>
            <version>2.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.ignite</groupId>
            <artifactId>ignite-spark</artifactId>
            <version>2.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-streaming_2.11</artifactId>
            <version>2.2.0</version>
        </dependency>

    </dependencies>
```

**Comment by dmagda** [comment]
Hello @pranasblk,

I could successfully upgrade the project to Apache Ignite 2.1 and make sure it works fine. Merged the changes.

However, the issue with Spark requires refreshment "ignite-spark" module. Filed the ticket:
https://issues.apache.org/jira/browse/IGNITE-6163

Hope it will be fixed soon. Anyway, you can update "ignite-spark" on your own and build Ignite from sources. If you contribute the change to Ignite code base it will be released faster.
